/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.simuladorautomovil.views;

import autonoma.simuladorautomovil.exception.ConfiguracionInvalidaException;
import autonoma.simuladorautomovil.models.Llanta;
import autonoma.simuladorautomovil.models.Motor;
import autonoma.simuladorautomovil.models.Taller;
import autonoma.simuladorautomovil.models.Vehiculo;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Asus
 */
public class VentanaTaller extends javax.swing.JDialog {

    /**
     * Creates new form VentanaTaller
     */
    private VentanaPrincipal ventana;
    public VentanaTaller(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.ventana=(VentanaPrincipal)parent;
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/simuladorautomovil/images/LogoCarro.png")).getImage());
        }catch(Exception e){
            
        }
        this.combLlantas.setModel(new DefaultComboBoxModel<>(Llanta.values()));
        this.combMotor.setModel(new DefaultComboBoxModel<>(Motor.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combMotor = new javax.swing.JComboBox<>();
        combLlantas = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnConfirmarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simuladorautomovil/images/Motor.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simuladorautomovil/images/Llantas.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel1.add(combMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 290, -1));

        combLlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combLlantasActionPerformed(evt);
            }
        });
        jPanel1.add(combLlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 290, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 110, -1));

        btnConfirmarCambios.setText("Confirmar cambios");
        btnConfirmarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCambiosActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combLlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combLlantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combLlantasActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCambiosActionPerformed
        
        Llanta llantaSeleccionada= (Llanta)this.combLlantas.getSelectedItem();
        Motor motorSeleccionado= (Motor)this.combMotor.getSelectedItem();
        Vehiculo carro = new Vehiculo(motorSeleccionado, llantaSeleccionada);
        Taller taller = new Taller();
        try {
            taller.actualizarConfiguracion(carro);
            this.ventana.actualizarConfiguracionVentana(carro);
        } catch (IOException ex) {
            Logger.getLogger(VentanaTaller.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnConfirmarCambiosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarCambios;
    private javax.swing.JComboBox<Llanta> combLlantas;
    private javax.swing.JComboBox<Motor> combMotor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
